config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { :sessions => "users/sessions"}
  devise_scope :user do
    root :to => 'devise/sessions#new'
  end

  #================================= Reports
  namespace :reports do
    get "dashboard" => "main#dashboard", as: :dashboard
    resources :surveillance, only: [:index] do
      collection do
         get :line_list
         get :simple_activity_line_list
         get :bogus_activity_line_list
         get :activity_duration
      end
    end
  end
  get "up" => "rails/health#show", as: :rails_health_check
  #nfs_picture_path
  get '/nfs_picture', to: 'ajax#nfs_picture'
  get 'ajax/populate_tehsil', to: 'ajax#populate_tehsil'
  get 'ajax/populate_uc', to: 'ajax#populate_uc'
  get '/ajax/populate_sub_departments', to: 'ajax#populate_sub_departments'
end

app/controllers/reports/main_controller.rb
class Reports::MainController < ApplicationController
    before_action :authenticate_user!

    def dashboard
    end
end

app/views/reports/main/shared/_header.html.erb
<header class="navbar navbar-expand-md navbar-light bg-light">
  <div class="container-xl">
    
    <!-- Brand / Logo -->
    <a class="navbar-brand" href="<%= root_path %>">
      <%= image_tag "logo_login.png", alt: "Logo", style:"height:40px" %>
    </a>

    <!-- Toggler (Hamburger) -->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar-menu" aria-controls="navbar-menu" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Collapsible Menu -->
    <div class="collapse navbar-collapse" id="navbar-menu">
      <ul class="navbar-nav me-auto">
        <!-- Home -->
        <li class="nav-item">
          <a class="nav-link" href="<%= root_path %>">
            <span class="nav-link-icon d-md-none d-lg-inline-block">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <path d="M5 12l-2 0l9 -9l9 9l-2 0"></path>
                <path d="M5 12v7a2 2 0 0 0 2 2h10a2 2 0 0 0 2 -2v-7"></path>
                <path d="M9 21v-6a2 2 0 0 1 2 -2h2a2 2 0 0 1 2 2v6"></path>
              </svg>
            </span>
            Home
          </a>
        </li>

        <!-- Dropdown -->
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarLayoutDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <span class="nav-link-icon d-md-none d-lg-inline-block">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="currentColor"
                stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <path d="M4 4m0 2a2 2 0 0 1 2 -2h2a2 2 0 0 1 2 2v1a2 2 0 0 1 -2 2h-2a2 2 0 0 1 -2 -2z"></path>
                <path d="M4 13m0 2a2 2 0 0 1 2 -2h2a2 2 0 0 1 2 2v3a2 2 0 0 1 -2 2h-2a2 2 0 0 1 -2 -2z"></path>
                <path d="M14 4m0 2a2 2 0 0 1 2 -2h2a2 2 0 0 1 2 2v3a2 2 0 0 1 -2 2h-2a2 2 0 0 1 -2 -2z"></path>
                <path d="M14 15m0 2a2 2 0 0 1 2 -2h2a2 2 0 0 1 2 2v1a2 2 0 0 1 -2 2h-2a2 2 0 0 1 -2 -2z"></path>
              </svg>
            </span>
            Surveillance
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarLayoutDropdown">
            <li><%= link_to "Patient Activity List", line_list_reports_surveillance_index_path, class:"dropdown-item" %></li>
            <li><%= link_to "Simple Activity List", simple_activity_line_list_reports_surveillance_index_path, class:"dropdown-item" %></li>
            <li><%= link_to "Bogus Activity List", bogus_activity_line_list_reports_surveillance_index_path, class:"dropdown-item" %></li>
            <li><%= link_to "Activation Duration Report", activity_duration_reports_surveillance_index_path, class:"dropdown-item" %></li>
          </ul>
        </li>
      </ul>

      <!-- Right Side -->
      <ul class="navbar-nav ms-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%= current_user.username %>
          </a>
          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="userDropdown">
            <li>
             <%= button_to destroy_user_session_path, method: :delete,
                data: { confirm: "Are you sure you want to logout?" },
                class: "dropdown-item d-flex align-items-center" do %>
                <i class="fa fa-unlock me-2"></i> Logout
              <% end %>
            </li>
          </ul>
        </li>
      </ul>

    </div>
  </div>
</header>